# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sy95exD6Lg_yg4UBYloRjAVD7BWxVMbH
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

X=np.array([[68],[104],[140],[176],[212]])
y=np.array([[20],[40],[60],[80],[100]])

model=LinearRegression()

model.fit(X,y)

model.predict([[100]])

model.score(X,y)

plt.scatter(X,y)
plt.plot(X,model.predict(X),color='purple')

model.coef_

model.intercept_